### ISSUE TITLE
invalid memory address or nil pointer dereference when accessing to npt existing path

### ISSUE THREAD

**Issue by pavel-odintsov** [omeid/go-resources#2]
Hello!

Thanks for nice code!

But I have found small mistake. 

When I trying to open resource which I haven't in my asset I got memory access issue:
```bash
Trying to open not existent resource
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x4ac2d1]

goroutine 1 [running]:
bytes.(*Reader).Read(0x0, 0xc8200a5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/reader.go:42 +0x61
bufio.(*Reader).Read(0xc820018120, 0xc8200a5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:197 +0x126
bufio.(*Scanner).Scan(0xc82004fed0, 0x1000)
	/usr/local/go/src/bufio/scan.go:180 +0x877
main.main()
	/root/fastnetmon/src/installer/selfbuild.go:39 +0x54b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
```

My code is:
```GO
package main

// Install:
// go get github.com/omeid/go-resources/cmd/resources

// Generate resources:
// resources -output="public_resources.go" -var="StaticResources" resources/*
// Build project:
// go build

import (
    "fmt"
    "net/http"
    "log"
    "bufio"
)

// All files from resources folder availible here
var StaticResources http.FileSystem 

func main() {
    if StaticResources == nil {
        log.Fatal("No StaticResources. Have you generated the resources?")   
    }

    fmt.Println("Trying to open not existent resource")
    static_resource, err := StaticResources.Open("/resources/nginx_gpg_signing_key.staticXXXX")
    if err != nil {
        log.Fatal("Could not open resource nginx_gpg_signing_key.static")
    }   
 
    defer static_resource.Close()

    reader := bufio.NewReader(static_resource)
    scanner := bufio.NewScanner(reader)

    for scanner.Scan() {
        fmt.Println(scanner.Text())
    }
}

```

**Comment by omeid** [comment]
Thanks for opening the issue and your kind words. I just pushed a fix that I believe addresses this issue. 

Please feel free to reopen the issue if the problem persists for you.

**Comment by pavel-odintsov** [comment]
That's fine! I have validated you fix and it's working really well! I'm really appreciate your help!
